//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.22 at 10:25:06 PM EEST 
//


package main.xmlClass.cars;

import main.xmlClass.EntityID;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Car complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Car">
 *   &lt;complexContent>
 *     &lt;extension base="{http://autoshop.com/details}Entity_ID">
 *       &lt;sequence>
 *         &lt;element name="Brand" type="{http://autoshop.com/details}ShortString"/>
 *         &lt;element name="Model" type="{http://autoshop.com/details}ShortString"/>
 *         &lt;element name="Year" type="{http://autoshop.com/details}Year"/>
 *         &lt;element name="Engine" type="{http://autoshop.com/details}Engine"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Car", propOrder = {
    "brand",
    "model",
    "year",
    "engine"
})
public class Car
    extends EntityID
{

    @XmlElement(name = "Brand", required = true)
    protected String brand;
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "Year")
    @XmlSchemaType(name = "integer")
    protected int year;
    @XmlElement(name = "Engine", required = true)
    protected Engine engine;

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the year property.
     *
     */
    public int getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     */
    public void setYear(int value) {
        this.year = value;
    }

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link Engine }
     *     
     */
    public Engine getEngine() {
        return engine;
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Engine }
     *     
     */
    public void setEngine(Engine value) {
        this.engine = value;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("\n\tCar#");
        builder.append(id);
        builder.append(" [brand=");
        builder.append(brand);
        builder.append(", model=");
        builder.append(model);
        builder.append(", year=");
        builder.append(year);
        builder.append(", engine=");
        builder.append(engine);
        builder.append("]");
        return builder.toString();
    }
}
