//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.22 at 10:25:06 PM EEST 
//


package main.xmlClass.cars;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Engine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Engine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="Cylinder" type="{http://autoshop.com/details}NonNegativeNumber"/>
 *           &lt;element name="Capacity" type="{http://autoshop.com/details}Decimal6_1"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="Power" type="{http://autoshop.com/details}Decimal6_1"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Engine", propOrder = {
    "cylinder",
    "capacity",
    "power"
})
public class Engine {

    @XmlElement(name = "Cylinder")
    protected BigInteger cylinder;
    @XmlElement(name = "Capacity")
    protected BigDecimal capacity;
    @XmlElement(name = "Power")
    protected BigDecimal power;

    /**
     * Gets the value of the cylinder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCylinder() {
        return cylinder;
    }

    /**
     * Sets the value of the cylinder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCylinder(BigInteger value) {
        this.cylinder = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCapacity(BigDecimal value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPower(BigDecimal value) {
        this.power = value;
    }


    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("\n\t\tEngine [capacity=");
        builder.append(capacity);
        builder.append(", cylinder=");
        builder.append(cylinder);
        builder.append(", power=");
        builder.append(power);
        builder.append("]");
        return builder.toString();
    }
}
